# Generated by Django 4.1.7 on 2023-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.IntegerField(),
        ),
    ]
